/**
 * Cultural Attractions Scraper
 * Real events from Pinecrest Gardens, The Bass, Jungle Island, Fairchild, etc.
 */

import { BaseScraper } from './base.js';
import type { RawEvent } from '../types.js';

interface RealEvent {
  title: string;
  date: string;
  time: string;
  venue: string;
  address: string;
  neighborhood: string;
  city?: 'Miami' | 'Fort Lauderdale';
  lat: number;
  lng: number;
  category: string;
  description: string;
  tags: string[];
  price: number;
  sourceUrl: string;
}

export class CulturalAttractionsScraper extends BaseScraper {
  private events: RealEvent[] = [
    // Jungle Island events
    {
      title: 'Survivor Ultimate Fan Cafe',
      date: '2026-01-30',
      time: '10:00',
      venue: 'Jungle Island',
      address: '1111 Parrot Jungle Trail, Miami, FL 33132',
      neighborhood: 'Watson Island',
      lat: 25.7856,
      lng: -80.1747,
      category: 'Community',
      description: 'Ultimate Survivor fan experience at Jungle Island. Meet fellow fans and enjoy themed activities.',
      tags: ['family-friendly', 'pop-up'],
      price: 45,
      sourceUrl: 'https://www.jungleisland.com/calendar-of-events/',
    },
    {
      title: 'Valentine\'s Sweet Fest',
      date: '2026-02-07',
      time: '10:00',
      venue: 'Jungle Island',
      address: '1111 Parrot Jungle Trail, Miami, FL 33132',
      neighborhood: 'Watson Island',
      lat: 25.7856,
      lng: -80.1747,
      category: 'Family',
      description: 'Valentine\'s celebration at Jungle Island with sweet treats, animal encounters, and family activities.',
      tags: ['family-friendly', 'seasonal'],
      price: 45,
      sourceUrl: 'https://www.jungleisland.com/calendar-of-events/',
    },
    // The Bass Museum events
    {
      title: 'The Bass Ball: Kaleidoscopic',
      date: '2026-03-07',
      time: '19:00',
      venue: 'The Bass Museum of Art',
      address: '2100 Collins Ave, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7956,
      lng: -80.1300,
      category: 'Art',
      description: 'Annual gala celebrating contemporary art. Cocktails, dinner, dancing, and art in Miami Beach\'s premier museum.',
      tags: ['art-gallery', 'local-favorite'],
      price: 500,
      sourceUrl: 'https://thebass.org/',
    },
    {
      title: 'Night at the Museum',
      date: '2026-02-14',
      time: '19:00',
      venue: 'The Bass Museum of Art',
      address: '2100 Collins Ave, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7956,
      lng: -80.1300,
      category: 'Art',
      description: 'After-hours museum experience with cocktails, music, and exclusive gallery access. Valentine\'s edition.',
      tags: ['art-gallery', 'museum', 'local-favorite'],
      price: 25,
      sourceUrl: 'https://thebass.org/',
    },
    {
      title: 'Breakfast at The Bass: Meet the Curator',
      date: '2026-02-08',
      time: '10:00',
      venue: 'The Bass Museum of Art',
      address: '2100 Collins Ave, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7956,
      lng: -80.1300,
      category: 'Art',
      description: 'Intimate breakfast with The Bass curator. Learn about current exhibitions and upcoming programming.',
      tags: ['art-gallery', 'museum', 'workshop'],
      price: 35,
      sourceUrl: 'https://thebass.org/',
    },
    // Pinecrest Gardens events
    {
      title: 'Pinecrest Gardens Farmers Market',
      date: '2026-01-19',
      time: '09:00',
      venue: 'Pinecrest Gardens',
      address: '11000 Red Rd, Pinecrest, FL 33156',
      neighborhood: 'Pinecrest',
      lat: 25.6667,
      lng: -80.3056,
      category: 'Food & Drink',
      description: 'Weekly farmers market with local produce, artisan goods, and live music in the botanical gardens.',
      tags: ['food-market', 'free-event', 'family-friendly', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.pinecrestgardens.org/',
    },
    {
      title: 'Pinecrest Gardens Farmers Market',
      date: '2026-01-26',
      time: '09:00',
      venue: 'Pinecrest Gardens',
      address: '11000 Red Rd, Pinecrest, FL 33156',
      neighborhood: 'Pinecrest',
      lat: 25.6667,
      lng: -80.3056,
      category: 'Food & Drink',
      description: 'Weekly farmers market with local produce, artisan goods, and live music in the botanical gardens.',
      tags: ['food-market', 'free-event', 'family-friendly', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.pinecrestgardens.org/',
    },
    // Fairchild Tropical Botanic Garden
    {
      title: 'Fairchild Chocolate Festival',
      date: '2026-01-25',
      time: '10:00',
      venue: 'Fairchild Tropical Botanic Garden',
      address: '10901 Old Cutler Rd, Coral Gables, FL 33156',
      neighborhood: 'Coral Gables',
      lat: 25.6767,
      lng: -80.2756,
      category: 'Food & Drink',
      description: 'Annual celebration of cacao and chocolate. Tastings, workshops, and tropical garden tours.',
      tags: ['food-market', 'family-friendly', 'local-favorite', 'festival'],
      price: 25,
      sourceUrl: 'https://fairchildgarden.org/',
    },
    {
      title: 'Fairchild Chocolate Festival',
      date: '2026-01-26',
      time: '10:00',
      venue: 'Fairchild Tropical Botanic Garden',
      address: '10901 Old Cutler Rd, Coral Gables, FL 33156',
      neighborhood: 'Coral Gables',
      lat: 25.6767,
      lng: -80.2756,
      category: 'Food & Drink',
      description: 'Annual celebration of cacao and chocolate. Tastings, workshops, and tropical garden tours.',
      tags: ['food-market', 'family-friendly', 'local-favorite', 'festival'],
      price: 25,
      sourceUrl: 'https://fairchildgarden.org/',
    },
    // SOBEWFF (South Beach Wine & Food Festival) - Feb 19-22, 2026
    {
      title: 'SOBEWFF Grand Tasting Village',
      date: '2026-02-21',
      time: '12:00',
      venue: 'Miami Beach Convention Center',
      address: '1901 Convention Center Dr, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7956,
      lng: -80.1389,
      category: 'Food & Drink',
      description: 'The signature SOBEWFF event. Sample dishes from top chefs, wine, spirits, and celebrity chef demos.',
      tags: ['food-market', 'wine-tasting', 'festival', 'local-favorite'],
      price: 225,
      sourceUrl: 'https://sobewff.org/',
    },
    {
      title: 'SOBEWFF Grand Tasting Village',
      date: '2026-02-22',
      time: '12:00',
      venue: 'Miami Beach Convention Center',
      address: '1901 Convention Center Dr, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7956,
      lng: -80.1389,
      category: 'Food & Drink',
      description: 'Day 2 of the signature SOBEWFF event. More chef demos, tastings, and culinary experiences.',
      tags: ['food-market', 'wine-tasting', 'festival', 'local-favorite'],
      price: 225,
      sourceUrl: 'https://sobewff.org/',
    },
    {
      title: 'SOBEWFF Burger Bash',
      date: '2026-02-20',
      time: '19:00',
      venue: 'Miami Beach',
      address: 'South Beach, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7825,
      lng: -80.1340,
      category: 'Food & Drink',
      description: 'Battle of the burgers. Top chefs compete for best burger while guests taste and vote.',
      tags: ['food-market', 'festival', 'local-favorite', 'beach'],
      price: 275,
      sourceUrl: 'https://sobewff.org/',
    },
    // Fruit & Spice Park
    {
      title: 'Redland Heritage Festival',
      date: '2026-02-07',
      time: '10:00',
      venue: 'Fruit & Spice Park',
      address: '24801 SW 187th Ave, Homestead, FL 33031',
      neighborhood: 'Homestead',
      lat: 25.5833,
      lng: -80.4833,
      category: 'Food & Drink',
      description: 'Celebrate the agricultural heritage of the Redland. Local produce, artisan crafts, and live music.',
      tags: ['food-market', 'family-friendly', 'local-favorite', 'festival'],
      price: 10,
      sourceUrl: 'https://www.miamidade.gov/global/park/fruit-and-spice-park.page',
    },
    // Joia Beach wellness
    {
      title: 'Sunrise Yoga at Joia Beach',
      date: '2026-01-25',
      time: '07:30',
      venue: 'Joia Beach',
      address: '1111 Parrot Jungle Trail, Miami, FL 33132',
      neighborhood: 'Watson Island',
      lat: 25.7856,
      lng: -80.1747,
      category: 'Wellness',
      description: 'Oceanside sunrise yoga at Joia Beach. Start your weekend with movement and ocean views.',
      tags: ['yoga', 'beach', 'sunrise', 'wellness'],
      price: 35,
      sourceUrl: 'https://joiabeachmiami.com/wellness/',
    },
    {
      title: 'Sound Healing at Joia Beach',
      date: '2026-02-01',
      time: '17:00',
      venue: 'Joia Beach',
      address: '1111 Parrot Jungle Trail, Miami, FL 33132',
      neighborhood: 'Watson Island',
      lat: 25.7856,
      lng: -80.1747,
      category: 'Wellness',
      description: 'Immersive sound healing session at sunset. Crystal bowls and ocean waves for deep relaxation.',
      tags: ['wellness', 'beach', 'meditation', 'sunset'],
      price: 45,
      sourceUrl: 'https://joiabeachmiami.com/wellness/',
    },
    // Miami Marathon
    {
      title: 'Life Time Miami Marathon & Half Marathon',
      date: '2026-01-25',
      time: '06:00',
      venue: 'Bayfront Park',
      address: '301 Biscayne Blvd, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7743,
      lng: -80.1867,
      category: 'Fitness',
      description: 'Annual Miami Marathon and Half Marathon. Scenic course through Miami with finish at Bayfront Park.',
      tags: ['running', 'outdoor', 'local-favorite', 'fitness-class'],
      price: 180,
      sourceUrl: 'https://www.themiamimarathon.com/',
    },
    // Key Biscayne events
    {
      title: 'Key Biscayne Film Festival',
      date: '2026-01-29',
      time: '18:00',
      venue: 'Key Biscayne Community Center',
      address: '10 Village Green Way, Key Biscayne, FL 33149',
      neighborhood: 'Key Biscayne',
      lat: 25.6936,
      lng: -80.1628,
      category: 'Culture',
      description: 'Annual film festival showcasing independent and international films. Multiple screenings over 4 days.',
      tags: ['film', 'local-favorite', 'festival'],
      price: 15,
      sourceUrl: 'https://business.keybiscaynechamber.org/events/details/key-biscayne-film-festival-23115',
    },
    {
      title: 'Key Biscayne Film Festival',
      date: '2026-01-30',
      time: '18:00',
      venue: 'Key Biscayne Community Center',
      address: '10 Village Green Way, Key Biscayne, FL 33149',
      neighborhood: 'Key Biscayne',
      lat: 25.6936,
      lng: -80.1628,
      category: 'Culture',
      description: 'Day 2 of the annual film festival. Independent and international film screenings.',
      tags: ['film', 'local-favorite', 'festival'],
      price: 15,
      sourceUrl: 'https://business.keybiscaynechamber.org/events/details/key-biscayne-film-festival-23115',
    },
    {
      title: 'Key Biscayne Film Festival',
      date: '2026-01-31',
      time: '18:00',
      venue: 'Key Biscayne Community Center',
      address: '10 Village Green Way, Key Biscayne, FL 33149',
      neighborhood: 'Key Biscayne',
      lat: 25.6936,
      lng: -80.1628,
      category: 'Culture',
      description: 'Day 3 of the annual film festival. Independent and international film screenings.',
      tags: ['film', 'local-favorite', 'festival'],
      price: 15,
      sourceUrl: 'https://business.keybiscaynechamber.org/events/details/key-biscayne-film-festival-23115',
    },
    {
      title: 'Key Biscayne Film Festival - Closing Night',
      date: '2026-02-01',
      time: '18:00',
      venue: 'Key Biscayne Community Center',
      address: '10 Village Green Way, Key Biscayne, FL 33149',
      neighborhood: 'Key Biscayne',
      lat: 25.6936,
      lng: -80.1628,
      category: 'Culture',
      description: 'Closing night of the Key Biscayne Film Festival with awards ceremony and final screenings.',
      tags: ['film', 'local-favorite', 'festival'],
      price: 20,
      sourceUrl: 'https://business.keybiscaynechamber.org/events/details/key-biscayne-film-festival-23115',
    },
    // Key Biscayne Farmers Market - every Saturday 9am-2pm
    {
      title: 'Key Biscayne Farmers Market',
      date: '2026-01-25',
      time: '09:00',
      venue: 'Key Biscayne Community Church',
      address: '355 Glenridge Rd, Key Biscayne, FL 33149',
      neighborhood: 'Key Biscayne',
      lat: 25.6936,
      lng: -80.1628,
      category: 'Food & Drink',
      description: 'Weekly Saturday farmers market with farm-fresh produce, artisan goods, and gourmet treats. Free admission.',
      tags: ['food-market', 'free-event', 'family-friendly', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.keybiscaynefarmersmarket.com/',
    },
    {
      title: 'Key Biscayne Farmers Market',
      date: '2026-02-01',
      time: '09:00',
      venue: 'Key Biscayne Community Church',
      address: '355 Glenridge Rd, Key Biscayne, FL 33149',
      neighborhood: 'Key Biscayne',
      lat: 25.6936,
      lng: -80.1628,
      category: 'Food & Drink',
      description: 'Weekly Saturday farmers market with farm-fresh produce, artisan goods, and gourmet treats. Free admission.',
      tags: ['food-market', 'free-event', 'family-friendly', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.keybiscaynefarmersmarket.com/',
    },
    {
      title: 'Key Biscayne Farmers Market',
      date: '2026-02-08',
      time: '09:00',
      venue: 'Key Biscayne Community Church',
      address: '355 Glenridge Rd, Key Biscayne, FL 33149',
      neighborhood: 'Key Biscayne',
      lat: 25.6936,
      lng: -80.1628,
      category: 'Food & Drink',
      description: 'Weekly Saturday farmers market with farm-fresh produce, artisan goods, and gourmet treats. Free admission.',
      tags: ['food-market', 'free-event', 'family-friendly', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.keybiscaynefarmersmarket.com/',
    },
    {
      title: 'Key Biscayne Farmers Market',
      date: '2026-02-15',
      time: '09:00',
      venue: 'Key Biscayne Community Church',
      address: '355 Glenridge Rd, Key Biscayne, FL 33149',
      neighborhood: 'Key Biscayne',
      lat: 25.6936,
      lng: -80.1628,
      category: 'Food & Drink',
      description: 'Weekly Saturday farmers market with farm-fresh produce, artisan goods, and gourmet treats. Free admission.',
      tags: ['food-market', 'free-event', 'family-friendly', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.keybiscaynefarmersmarket.com/',
    },
    {
      title: 'Key Biscayne Farmers Market',
      date: '2026-02-22',
      time: '09:00',
      venue: 'Key Biscayne Community Church',
      address: '355 Glenridge Rd, Key Biscayne, FL 33149',
      neighborhood: 'Key Biscayne',
      lat: 25.6936,
      lng: -80.1628,
      category: 'Food & Drink',
      description: 'Weekly Saturday farmers market with farm-fresh produce, artisan goods, and gourmet treats. Free admission.',
      tags: ['food-market', 'free-event', 'family-friendly', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.keybiscaynefarmersmarket.com/',
    },
    {
      title: 'Key Biscayne Farmers Market',
      date: '2026-03-01',
      time: '09:00',
      venue: 'Key Biscayne Community Church',
      address: '355 Glenridge Rd, Key Biscayne, FL 33149',
      neighborhood: 'Key Biscayne',
      lat: 25.6936,
      lng: -80.1628,
      category: 'Food & Drink',
      description: 'Weekly Saturday farmers market with farm-fresh produce, artisan goods, and gourmet treats. Free admission.',
      tags: ['food-market', 'free-event', 'family-friendly', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.keybiscaynefarmersmarket.com/',
    },
    {
      title: 'La Feria de Sevilla en Miami',
      date: '2026-03-14',
      time: '12:00',
      venue: 'Key Biscayne',
      address: 'Crandon Park, Key Biscayne, FL 33149',
      neighborhood: 'Key Biscayne',
      lat: 25.7089,
      lng: -80.1528,
      category: 'Culture',
      description: 'Traditional Spanish festival celebrating Seville culture with flamenco, tapas, and live music.',
      tags: ['latin', 'festival', 'dancing', 'local-favorite'],
      price: 25,
      sourceUrl: 'https://business.keybiscaynechamber.org/events/details/la-feria-de-sevilla-en-miami-23298',
    },
    {
      title: 'Art by the Sea',
      date: '2026-03-22',
      time: '10:00',
      venue: 'Crandon Park',
      address: '6747 Crandon Blvd, Key Biscayne, FL 33149',
      neighborhood: 'Key Biscayne',
      lat: 25.7089,
      lng: -80.1528,
      category: 'Art',
      description: 'Outdoor art festival on Key Biscayne featuring local and regional artists, live music, and ocean views.',
      tags: ['art-gallery', 'beach', 'outdoor', 'family-friendly', 'festival'],
      price: 0,
      sourceUrl: 'https://business.keybiscaynechamber.org/events/details/art-by-the-sea-23300',
    },
    // FTL War Memorial events
    {
      title: 'Panthers Watch Party vs Blues',
      date: '2026-01-29',
      time: '18:00',
      venue: 'FTL War Memorial',
      address: '800 NE 8th St, Fort Lauderdale, FL 33304',
      neighborhood: 'Fort Lauderdale',
      city: 'Fort Lauderdale',
      lat: 26.1289,
      lng: -80.1367,
      category: 'Sports',
      description: 'Florida Panthers Watch Party presented by Yuengling. Open skating 6-8pm before puck drop at 8pm vs St. Louis Blues. Mascot appearances, giveaways, big screen viewing.',
      tags: ['local-favorite', 'community'],
      price: 15,
      sourceUrl: 'https://www.ftlwarmemorial.com/events/detail/watch-party',
    },
    {
      title: 'Sabaton: Legends On Tour',
      date: '2026-02-09',
      time: '19:00',
      venue: 'FTL War Memorial',
      address: '800 NE 8th St, Fort Lauderdale, FL 33304',
      neighborhood: 'Fort Lauderdale',
      city: 'Fort Lauderdale',
      lat: 26.1289,
      lng: -80.1367,
      category: 'Music',
      description: 'Swedish heavy metal band Sabaton with support from Pop Evil and Wings of Steel.',
      tags: ['live-music', 'local-favorite'],
      price: 50,
      sourceUrl: 'https://www.ftlwarmemorial.com/events',
    },
    {
      title: 'Valentine\'s Date Skate',
      date: '2026-02-14',
      time: '19:00',
      venue: 'FTL War Memorial',
      address: '800 NE 8th St, Fort Lauderdale, FL 33304',
      neighborhood: 'Fort Lauderdale',
      city: 'Fort Lauderdale',
      lat: 26.1289,
      lng: -80.1367,
      category: 'Community',
      description: 'Valentine\'s Day ice skating at the War Memorial. Romantic evening on the ice.',
      tags: ['local-favorite', 'community'],
      price: 20,
      sourceUrl: 'https://www.ftlwarmemorial.com/events',
    },
    {
      title: '4 Nations Face-Off Watch: Finland vs Sweden',
      date: '2026-02-15',
      time: '13:00',
      venue: 'FTL War Memorial',
      address: '800 NE 8th St, Fort Lauderdale, FL 33304',
      neighborhood: 'Fort Lauderdale',
      city: 'Fort Lauderdale',
      lat: 26.1289,
      lng: -80.1367,
      category: 'Sports',
      description: '4 Nations Face-Off Watch & Skate. Finland vs Sweden on the big screens. Skating, shopping at Pantherland, cocktails at The Federal.',
      tags: ['local-favorite', 'community'],
      price: 15,
      sourceUrl: 'https://www.ftlwarmemorial.com/events/detail/skate-watch-4-nations-face-off',
    },
    {
      title: '4 Nations Face-Off Watch: USA vs Canada',
      date: '2026-02-15',
      time: '20:00',
      venue: 'FTL War Memorial',
      address: '800 NE 8th St, Fort Lauderdale, FL 33304',
      neighborhood: 'Fort Lauderdale',
      city: 'Fort Lauderdale',
      lat: 26.1289,
      lng: -80.1367,
      category: 'Sports',
      description: '4 Nations Face-Off Watch & Skate. USA vs Canada showdown on the big screens. Skating, shopping, and cocktails.',
      tags: ['local-favorite', 'community'],
      price: 15,
      sourceUrl: 'https://www.ftlwarmemorial.com/events/detail/skate-watch-4-nations-face-off',
    },
    {
      title: '4 Nations Face-Off Watch: Canada vs Finland',
      date: '2026-02-17',
      time: '13:00',
      venue: 'FTL War Memorial',
      address: '800 NE 8th St, Fort Lauderdale, FL 33304',
      neighborhood: 'Fort Lauderdale',
      city: 'Fort Lauderdale',
      lat: 26.1289,
      lng: -80.1367,
      category: 'Sports',
      description: '4 Nations Face-Off Watch & Skate. Canada vs Finland on the big screens. Skating, Pantherland shopping, cocktails at The Federal.',
      tags: ['local-favorite', 'community'],
      price: 15,
      sourceUrl: 'https://www.ftlwarmemorial.com/events/detail/skate-watch-4-nations-face-off',
    },
    {
      title: 'Thee Phantom and The Illharmonics',
      date: '2026-03-07',
      time: '20:00',
      venue: 'FTL War Memorial',
      address: '800 NE 8th St, Fort Lauderdale, FL 33304',
      neighborhood: 'Fort Lauderdale',
      city: 'Fort Lauderdale',
      lat: 26.1289,
      lng: -80.1367,
      category: 'Music',
      description: 'Live music performance at the War Memorial Auditorium.',
      tags: ['live-music'],
      price: 35,
      sourceUrl: 'https://www.ftlwarmemorial.com/events',
    },
    {
      title: 'Cat\'s Cup Street Hockey Tournament',
      date: '2026-03-21',
      time: '09:00',
      venue: 'Amerant Bank Arena',
      address: '1 Panther Pkwy, Sunrise, FL 33323',
      neighborhood: 'Sunrise',
      city: 'Fort Lauderdale',
      lat: 26.1584,
      lng: -80.3256,
      category: 'Sports',
      description: 'South Florida\'s largest street hockey festival. Adult tournament presented by Coors Light & Youth tournament powered by Verizon.',
      tags: ['family-friendly', 'festival', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.ftlwarmemorial.com/events/detail/cats-cup',
    },
    {
      title: 'Cat\'s Cup Street Hockey Tournament',
      date: '2026-03-22',
      time: '09:00',
      venue: 'Amerant Bank Arena',
      address: '1 Panther Pkwy, Sunrise, FL 33323',
      neighborhood: 'Sunrise',
      city: 'Fort Lauderdale',
      lat: 26.1584,
      lng: -80.3256,
      category: 'Sports',
      description: 'Day 2 of South Florida\'s largest street hockey festival. Finals and championship games.',
      tags: ['family-friendly', 'festival', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.ftlwarmemorial.com/events/detail/cats-cup',
    },
    {
      title: 'An Evening with Goose',
      date: '2026-04-14',
      time: '19:30',
      venue: 'FTL War Memorial',
      address: '800 NE 8th St, Fort Lauderdale, FL 33304',
      neighborhood: 'Fort Lauderdale',
      city: 'Fort Lauderdale',
      lat: 26.1289,
      lng: -80.1367,
      category: 'Music',
      description: 'Jam band Goose brings their improvisational rock to Fort Lauderdale. Night 1 of 2.',
      tags: ['live-music', 'local-favorite'],
      price: 65,
      sourceUrl: 'https://www.ftlwarmemorial.com/events',
    },
    {
      title: 'An Evening with Goose',
      date: '2026-04-15',
      time: '19:30',
      venue: 'FTL War Memorial',
      address: '800 NE 8th St, Fort Lauderdale, FL 33304',
      neighborhood: 'Fort Lauderdale',
      city: 'Fort Lauderdale',
      lat: 26.1289,
      lng: -80.1367,
      category: 'Music',
      description: 'Jam band Goose brings their improvisational rock to Fort Lauderdale. Night 2 of 2.',
      tags: ['live-music', 'local-favorite'],
      price: 65,
      sourceUrl: 'https://www.ftlwarmemorial.com/events',
    },
    // Miami Dolphins Draft Party
    {
      title: 'Dolphins Draft Party',
      date: '2026-04-23',
      time: '19:00',
      venue: 'The Doral Yard',
      address: '8455 NW 53rd St, Doral, FL 33166',
      neighborhood: 'Doral',
      lat: 25.8167,
      lng: -80.3389,
      category: 'Sports',
      description: 'Miami Dolphins NFL Draft Watch Party presented by Bud Light. Expert panel discussions, Dolphins alumni appearances, cheerleaders, mascot, and giveaways.',
      tags: ['local-favorite', 'community'],
      price: 0,
      sourceUrl: 'https://www.miamidolphins.com/draft/2025/dolphins-draft-party',
    },
    // Formula 1 Miami Grand Prix 2026
    {
      title: 'F1 Miami Grand Prix - Practice & Sprint Qualifying',
      date: '2026-05-01',
      time: '13:30',
      venue: 'Miami International Autodrome',
      address: '347 Don Shula Dr, Miami Gardens, FL 33056',
      neighborhood: 'Miami Gardens',
      lat: 25.9581,
      lng: -80.2389,
      category: 'Sports',
      description: 'Formula 1 Miami Grand Prix Day 1. Practice 1 at 1:30pm, Sprint Qualifying at 5:30pm. Support races include Porsche Carrera Cup and McLaren Trophy.',
      tags: ['local-favorite', 'festival'],
      price: 200,
      sourceUrl: 'https://www.f1miamiusa.com/',
    },
    {
      title: 'F1 Miami Grand Prix - Sprint Race & Qualifying',
      date: '2026-05-02',
      time: '13:00',
      venue: 'Miami International Autodrome',
      address: '347 Don Shula Dr, Miami Gardens, FL 33056',
      neighborhood: 'Miami Gardens',
      lat: 25.9581,
      lng: -80.2389,
      category: 'Sports',
      description: 'Formula 1 Miami Grand Prix Day 2. F1 Sprint at 1pm, Qualifying at 5pm. Fan zones, entertainment, and world-class racing.',
      tags: ['local-favorite', 'festival'],
      price: 200,
      sourceUrl: 'https://www.f1miamiusa.com/',
    },
    {
      title: 'F1 Miami Grand Prix - Race Day',
      date: '2026-05-03',
      time: '17:00',
      venue: 'Miami International Autodrome',
      address: '347 Don Shula Dr, Miami Gardens, FL 33056',
      neighborhood: 'Miami Gardens',
      lat: 25.9581,
      lng: -80.2389,
      category: 'Sports',
      description: 'Formula 1 Miami Grand Prix Race Day. 57 laps around the 3.36-mile circuit. The biggest motorsport event in South Florida.',
      tags: ['local-favorite', 'festival'],
      price: 300,
      sourceUrl: 'https://www.f1miamiusa.com/',
    },
    // O Cinema events
    {
      title: 'Miami Jewish Film Festival',
      date: '2026-01-19',
      time: '14:00',
      venue: 'O Cinema South Beach',
      address: '1130 Washington Ave, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7789,
      lng: -80.1356,
      category: 'Culture',
      description: 'Miami Jewish Film Festival at O Cinema South Beach. Diverse programming of narrative, documentary, and short films.',
      tags: ['film', 'local-favorite', 'festival'],
      price: 15,
      sourceUrl: 'https://www.o-cinema.org',
    },
    {
      title: 'Miami Jewish Film Festival',
      date: '2026-01-20',
      time: '14:00',
      venue: 'O Cinema South Beach',
      address: '1130 Washington Ave, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7789,
      lng: -80.1356,
      category: 'Culture',
      description: 'Miami Jewish Film Festival at O Cinema South Beach. Diverse programming of narrative, documentary, and short films.',
      tags: ['film', 'local-favorite', 'festival'],
      price: 15,
      sourceUrl: 'https://www.o-cinema.org',
    },
    {
      title: 'Miami Jewish Film Festival',
      date: '2026-01-21',
      time: '14:00',
      venue: 'O Cinema South Beach',
      address: '1130 Washington Ave, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7789,
      lng: -80.1356,
      category: 'Culture',
      description: 'Miami Jewish Film Festival at O Cinema South Beach. Diverse programming of narrative, documentary, and short films.',
      tags: ['film', 'local-favorite', 'festival'],
      price: 15,
      sourceUrl: 'https://www.o-cinema.org',
    },
    {
      title: 'Miami Jewish Film Festival',
      date: '2026-01-22',
      time: '14:00',
      venue: 'O Cinema South Beach',
      address: '1130 Washington Ave, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7789,
      lng: -80.1356,
      category: 'Culture',
      description: 'Miami Jewish Film Festival at O Cinema South Beach. Diverse programming of narrative, documentary, and short films.',
      tags: ['film', 'local-favorite', 'festival'],
      price: 15,
      sourceUrl: 'https://www.o-cinema.org',
    },
    {
      title: 'The Secret Agent',
      date: '2026-01-19',
      time: '18:00',
      venue: 'O Cinema South Beach',
      address: '1130 Washington Ave, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7789,
      lng: -80.1356,
      category: 'Culture',
      description: 'Film screening at O Cinema South Beach, Miami\'s beloved independent cinema.',
      tags: ['film', 'local-favorite'],
      price: 14,
      sourceUrl: 'https://www.o-cinema.org',
    },
    {
      title: 'Sundance Film Festival Short Film Tour',
      date: '2026-01-23',
      time: '19:00',
      venue: 'O Cinema South Beach',
      address: '1130 Washington Ave, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7789,
      lng: -80.1356,
      category: 'Culture',
      description: 'A curated selection of short films from the Sundance Film Festival. Experience indie cinema at its finest.',
      tags: ['film', 'local-favorite', 'festival'],
      price: 14,
      sourceUrl: 'https://www.o-cinema.org',
    },
    {
      title: 'To Wong Foo, Thanks for Everything! Julie Newmar',
      date: '2026-01-29',
      time: '21:00',
      venue: 'O Cinema South Beach',
      address: '1130 Washington Ave, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7789,
      lng: -80.1356,
      category: 'Culture',
      description: 'Classic film screening of the 1995 drag queen road comedy starring Wesley Snipes, Patrick Swayze, and John Leguizamo.',
      tags: ['film', 'local-favorite'],
      price: 14,
      sourceUrl: 'https://www.o-cinema.org',
    },
    {
      title: 'No Other Choice',
      date: '2026-01-30',
      time: '19:00',
      venue: 'O Cinema South Beach',
      address: '1130 Washington Ave, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7789,
      lng: -80.1356,
      category: 'Culture',
      description: 'Film premiere at O Cinema South Beach.',
      tags: ['film', 'local-favorite'],
      price: 14,
      sourceUrl: 'https://www.o-cinema.org',
    },
    {
      title: 'Pariah',
      date: '2026-02-19',
      time: '19:00',
      venue: 'O Cinema South Beach',
      address: '1130 Washington Ave, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7789,
      lng: -80.1356,
      category: 'Culture',
      description: 'Screening of Dee Rees\' acclaimed coming-of-age drama about a Brooklyn teenager embracing her identity.',
      tags: ['film', 'local-favorite'],
      price: 14,
      sourceUrl: 'https://www.o-cinema.org',
    },
    // Rooftop Cinema Club South Beach
    {
      title: 'Rooftop Cinema: The Princess Bride',
      date: '2026-01-19',
      time: '20:00',
      venue: 'Rooftop Cinema Club South Beach',
      address: '1111 Lincoln Rd, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7906,
      lng: -80.1400,
      category: 'Culture',
      description: 'Classic film under the stars on a Miami Beach rooftop. Blankets, headphones, and stunning views included.',
      tags: ['film', 'rooftop', 'local-favorite'],
      price: 25,
      sourceUrl: 'https://rooftopcinemaclub.com/miami/',
    },
    {
      title: 'Rooftop Cinema: The Notebook',
      date: '2026-01-21',
      time: '20:00',
      venue: 'Rooftop Cinema Club South Beach',
      address: '1111 Lincoln Rd, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7906,
      lng: -80.1400,
      category: 'Culture',
      description: 'Romantic classic under the stars. Rooftop cinema experience with blankets, headphones, and city views.',
      tags: ['film', 'rooftop', 'local-favorite'],
      price: 25,
      sourceUrl: 'https://rooftopcinemaclub.com/miami/',
    },
    {
      title: 'Rooftop Cinema: Pulp Fiction',
      date: '2026-01-23',
      time: '21:55',
      venue: 'Rooftop Cinema Club South Beach',
      address: '1111 Lincoln Rd, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7906,
      lng: -80.1400,
      category: 'Culture',
      description: 'Tarantino classic on a Miami Beach rooftop. Premium outdoor cinema experience.',
      tags: ['film', 'rooftop', 'local-favorite'],
      price: 25,
      sourceUrl: 'https://rooftopcinemaclub.com/miami/',
    },
    {
      title: 'Rooftop Cinema: Pretty Woman',
      date: '2026-01-24',
      time: '19:45',
      venue: 'Rooftop Cinema Club South Beach',
      address: '1111 Lincoln Rd, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7906,
      lng: -80.1400,
      category: 'Culture',
      description: 'Romantic comedy classic under the Miami stars. Rooftop cinema with stunning views.',
      tags: ['film', 'rooftop', 'local-favorite'],
      price: 25,
      sourceUrl: 'https://rooftopcinemaclub.com/miami/',
    },
    {
      title: 'Rooftop Cinema: Scarface',
      date: '2026-01-25',
      time: '19:45',
      venue: 'Rooftop Cinema Club South Beach',
      address: '1111 Lincoln Rd, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7906,
      lng: -80.1400,
      category: 'Culture',
      description: 'The Miami crime classic on a Miami Beach rooftop. Premium outdoor cinema experience.',
      tags: ['film', 'rooftop', 'local-favorite'],
      price: 25,
      sourceUrl: 'https://rooftopcinemaclub.com/miami/',
    },
    {
      title: 'Rooftop Cinema: Big Game Watch Party',
      date: '2026-02-08',
      time: '18:00',
      venue: 'Rooftop Cinema Club South Beach',
      address: '1111 Lincoln Rd, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7906,
      lng: -80.1400,
      category: 'Sports',
      description: 'Watch the Big Game on a Miami Beach rooftop with stunning views and premium amenities.',
      tags: ['rooftop', 'local-favorite', 'community'],
      price: 45,
      sourceUrl: 'https://rooftopcinemaclub.com/miami/',
    },
    // NWS Wallcast Concerts - Free outdoor concerts
    {
      title: 'NWS Wallcast: Marcus Roberts Trio',
      date: '2026-01-10',
      time: '19:30',
      venue: 'Soundscape Park',
      address: '500 17th St, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7899,
      lng: -80.1348,
      category: 'Music',
      description: 'Free outdoor Wallcast concert. Jazz meets classical as the Marcus Roberts Trio joins New World Symphony. Bring blankets and picnic.',
      tags: ['live-music', 'free-event', 'outdoor', 'park', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.nws.edu/events-tickets/wallcast-concerts-and-park-events/',
    },
    {
      title: 'NWS Wallcast: John Adams with Stéphane Denève',
      date: '2026-01-17',
      time: '19:30',
      venue: 'Soundscape Park',
      address: '500 17th St, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7899,
      lng: -80.1348,
      category: 'Music',
      description: 'Free outdoor Wallcast. Composer John Adams appears with conductor Stéphane Denève for an evening of contemporary American classical music.',
      tags: ['live-music', 'free-event', 'outdoor', 'park', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.nws.edu/events-tickets/wallcast-concerts-and-park-events/',
    },
    {
      title: 'NWS Wallcast: Claire Chase',
      date: '2026-01-25',
      time: '19:30',
      venue: 'Soundscape Park',
      address: '500 17th St, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7899,
      lng: -80.1348,
      category: 'Music',
      description: 'Free outdoor Wallcast. Pioneering flutist Claire Chase pushes the boundaries of her ancient instrument.',
      tags: ['live-music', 'free-event', 'outdoor', 'park', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.nws.edu/events-tickets/wallcast-concerts-and-park-events/',
    },
    {
      title: 'NWS Wallcast: Identity, Justice & Resilience',
      date: '2026-02-21',
      time: '19:30',
      venue: 'Soundscape Park',
      address: '500 17th St, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7899,
      lng: -80.1348,
      category: 'Music',
      description: 'Free outdoor Wallcast. Contemporary classical blends with protest, gospel and American history in this powerful program.',
      tags: ['live-music', 'free-event', 'outdoor', 'park', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.nws.edu/events-tickets/wallcast-concerts-and-park-events/',
    },
    {
      title: 'NWS Wallcast: Love, Poetry & Myth',
      date: '2026-03-07',
      time: '19:30',
      venue: 'Soundscape Park',
      address: '500 17th St, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7899,
      lng: -80.1348,
      category: 'Music',
      description: 'Free outdoor Wallcast. Orchestral color and vocal expression unite in a program centered on love, poetry and myth.',
      tags: ['live-music', 'free-event', 'outdoor', 'park', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.nws.edu/events-tickets/wallcast-concerts-and-park-events/',
    },
    {
      title: 'NWS Wallcast: Hollywood & Classical Roots',
      date: '2026-03-14',
      time: '19:30',
      venue: 'Soundscape Park',
      address: '500 17th St, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7899,
      lng: -80.1348,
      category: 'Music',
      description: 'Free outdoor Wallcast. Familiar film themes meet bold orchestral works exploring early Hollywood\'s classical roots.',
      tags: ['live-music', 'free-event', 'outdoor', 'park', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.nws.edu/events-tickets/wallcast-concerts-and-park-events/',
    },
    {
      title: 'NWS Wallcast: American Chamber Music',
      date: '2026-03-22',
      time: '19:30',
      venue: 'Soundscape Park',
      address: '500 17th St, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7899,
      lng: -80.1348,
      category: 'Music',
      description: 'Free outdoor Wallcast. Explore American chamber music from colonial-era compositions to groundbreaking 20th-century works.',
      tags: ['live-music', 'free-event', 'outdoor', 'park', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.nws.edu/events-tickets/wallcast-concerts-and-park-events/',
    },
    {
      title: 'NWS Wallcast: American Dance Odyssey with Miami City Ballet',
      date: '2026-04-18',
      time: '20:00',
      venue: 'Soundscape Park',
      address: '500 17th St, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7899,
      lng: -80.1348,
      category: 'Culture',
      description: 'Free outdoor Wallcast. Stéphane Denève conducts with Miami City Ballet in an American dance celebration.',
      tags: ['live-music', 'free-event', 'outdoor', 'park', 'local-favorite', 'dancing'],
      price: 0,
      sourceUrl: 'https://www.nws.edu/events-tickets/wallcast-concerts-and-park-events/',
    },
    {
      title: 'NWS Wallcast: Bernstein & Gershwin',
      date: '2026-05-02',
      time: '20:00',
      venue: 'Soundscape Park',
      address: '500 17th St, Miami Beach, FL 33139',
      neighborhood: 'South Beach',
      lat: 25.7899,
      lng: -80.1348,
      category: 'Music',
      description: 'Free outdoor Wallcast. Stéphane Denève and Jean-Yves Thibaudet perform Bernstein\'s Candide, Age of Anxiety, and Gershwin\'s An American in Paris.',
      tags: ['live-music', 'free-event', 'outdoor', 'park', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://www.nws.edu/events-tickets/wallcast-concerts-and-park-events/',
    },
    // Luminosa at Jungle Island - Light Festival
    {
      title: 'Luminosa: A Journey Through Light',
      date: '2026-01-24',
      time: '17:30',
      venue: 'Jungle Island',
      address: '1111 Parrot Jungle Trail, Miami, FL 33132',
      neighborhood: 'Watson Island',
      lat: 25.7856,
      lng: -80.1747,
      category: 'Art',
      description: 'Spectacular outdoor lantern festival with 160 tons of steel, 200,000 feet of silk fabric, and nearly a million LED lights. Journey through the Amazon, African savannah, Ancient Egypt and Frozen Kingdom.',
      tags: ['art-gallery', 'family-friendly', 'outdoor', 'local-favorite'],
      price: 31,
      sourceUrl: 'https://luminosamiami.com/',
    },
    {
      title: 'Luminosa: A Journey Through Light',
      date: '2026-01-25',
      time: '17:30',
      venue: 'Jungle Island',
      address: '1111 Parrot Jungle Trail, Miami, FL 33132',
      neighborhood: 'Watson Island',
      lat: 25.7856,
      lng: -80.1747,
      category: 'Art',
      description: 'Spectacular outdoor lantern festival with 160 tons of steel, 200,000 feet of silk fabric, and nearly a million LED lights. Journey through the Amazon, African savannah, Ancient Egypt and Frozen Kingdom.',
      tags: ['art-gallery', 'family-friendly', 'outdoor', 'local-favorite'],
      price: 47,
      sourceUrl: 'https://luminosamiami.com/',
    },
    {
      title: 'Luminosa: A Journey Through Light',
      date: '2026-01-31',
      time: '17:30',
      venue: 'Jungle Island',
      address: '1111 Parrot Jungle Trail, Miami, FL 33132',
      neighborhood: 'Watson Island',
      lat: 25.7856,
      lng: -80.1747,
      category: 'Art',
      description: 'Spectacular outdoor lantern festival. Final weeks - runs through March 7.',
      tags: ['art-gallery', 'family-friendly', 'outdoor', 'local-favorite'],
      price: 47,
      sourceUrl: 'https://luminosamiami.com/',
    },
    {
      title: 'Luminosa: A Journey Through Light',
      date: '2026-02-07',
      time: '17:30',
      venue: 'Jungle Island',
      address: '1111 Parrot Jungle Trail, Miami, FL 33132',
      neighborhood: 'Watson Island',
      lat: 25.7856,
      lng: -80.1747,
      category: 'Art',
      description: 'Spectacular outdoor lantern festival. Journey through the Amazon, African savannah, Ancient Egypt and Frozen Kingdom.',
      tags: ['art-gallery', 'family-friendly', 'outdoor', 'local-favorite'],
      price: 47,
      sourceUrl: 'https://luminosamiami.com/',
    },
    {
      title: 'Luminosa: A Journey Through Light',
      date: '2026-02-14',
      time: '17:30',
      venue: 'Jungle Island',
      address: '1111 Parrot Jungle Trail, Miami, FL 33132',
      neighborhood: 'Watson Island',
      lat: 25.7856,
      lng: -80.1747,
      category: 'Art',
      description: 'Valentine\'s Day at Luminosa. Spectacular outdoor lantern festival - romantic evening under the lights.',
      tags: ['art-gallery', 'family-friendly', 'outdoor', 'local-favorite'],
      price: 47,
      sourceUrl: 'https://luminosamiami.com/',
    },
    // Pegasus World Cup
    {
      title: 'Pegasus World Cup',
      date: '2026-01-24',
      time: '11:00',
      venue: 'Gulfstream Park',
      address: '901 S Federal Hwy, Hallandale Beach, FL 33009',
      neighborhood: 'Hallandale Beach',
      lat: 25.9706,
      lng: -80.1489,
      category: 'Sports',
      description: '10th anniversary of horse racing\'s hottest event. $3M Championship race at 5:45pm. Live on NBC. Performances by Black Coffee and Diplo.',
      tags: ['local-favorite', 'live-music', 'festival'],
      price: 50,
      sourceUrl: 'https://www.pegasusworldcup.com/',
    },
    // Coconut Grove Arts Festival
    {
      title: 'Coconut Grove Arts Festival',
      date: '2026-02-14',
      time: '10:00',
      venue: 'Regatta Park',
      address: 'Pan American Dr, Coconut Grove, FL 33133',
      neighborhood: 'Coconut Grove',
      lat: 25.7267,
      lng: -80.2378,
      category: 'Art',
      description: '62nd annual arts festival. 285+ artists, live performances, family activities. Overlooking Biscayne Bay at Dinner Key Marina.',
      tags: ['art-gallery', 'outdoor', 'family-friendly', 'festival', 'local-favorite'],
      price: 30,
      sourceUrl: 'https://cgaf.com/',
    },
    {
      title: 'Coconut Grove Arts Festival',
      date: '2026-02-15',
      time: '10:00',
      venue: 'Regatta Park',
      address: 'Pan American Dr, Coconut Grove, FL 33133',
      neighborhood: 'Coconut Grove',
      lat: 25.7267,
      lng: -80.2378,
      category: 'Art',
      description: '62nd annual arts festival. 285+ artists across 12+ mediums from painting to sculpture. Live entertainment and culinary arts.',
      tags: ['art-gallery', 'outdoor', 'family-friendly', 'festival', 'local-favorite'],
      price: 30,
      sourceUrl: 'https://cgaf.com/',
    },
    {
      title: 'Coconut Grove Arts Festival',
      date: '2026-02-16',
      time: '10:00',
      venue: 'Regatta Park',
      address: 'Pan American Dr, Coconut Grove, FL 33133',
      neighborhood: 'Coconut Grove',
      lat: 25.7267,
      lng: -80.2378,
      category: 'Art',
      description: 'Final day of 62nd annual arts festival. Presidents Day weekend celebration of visual arts on the Coconut Grove waterfront.',
      tags: ['art-gallery', 'outdoor', 'family-friendly', 'festival', 'local-favorite'],
      price: 30,
      sourceUrl: 'https://cgaf.com/',
    },
  ];

  constructor() {
    super('Cultural Attractions', { weight: 1.4, rateLimit: 0 });
  }

  async scrape(): Promise<RawEvent[]> {
    this.log(`Processing ${this.events.length} cultural attraction events...`);

    return this.events.map((event) => ({
      title: event.title,
      startAt: `${event.date}T${event.time}:00`,
      venueName: event.venue,
      address: event.address,
      neighborhood: event.neighborhood,
      lat: event.lat,
      lng: event.lng,
      city: event.city || 'Miami',
      tags: event.tags,
      category: event.category,
      priceLabel: event.price === 0 ? 'Free' : event.price > 100 ? '$$$' : event.price > 30 ? '$$' : '$',
      priceAmount: event.price,
      isOutdoor: event.tags.includes('beach') || event.tags.includes('park') || event.tags.includes('food-market'),
      description: event.description,
      sourceUrl: event.sourceUrl,
      sourceName: this.name,
      ticketUrl: event.sourceUrl,
      recurring: false,
    }));
  }
}
