/**
 * Real Venue Events Scraper
 * Actual scheduled events from venues with real artist/event names
 * Updated periodically from venue websites
 */

import { BaseScraper } from './base.js';
import type { RawEvent } from '../types.js';

interface RealEvent {
  title: string;
  date: string; // YYYY-MM-DD
  time: string; // HH:MM
  venue: string;
  address: string;
  neighborhood: string;
  lat: number;
  lng: number;
  city: 'Miami' | 'Fort Lauderdale';
  category: string;
  description: string;
  tags: string[];
  price: number;
  sourceUrl: string;
  ticketUrl?: string;
}

export class RealVenueEventsScraper extends BaseScraper {
  // Real events from Zey Zey - https://zeyzeymiami.com/tickets/
  private zeyZeyEvents: RealEvent[] = [
    {
      title: 'CFP Championship Final Watch Party',
      date: '2026-01-19',
      time: '18:00',
      venue: 'Zey Zey',
      address: '233 NE 2nd St, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7751,
      lng: -80.1897,
      city: 'Miami',
      category: 'Sports',
      description: 'Watch the College Football Playoff Championship at Zey Zey. Big screens, great drinks, electric atmosphere.',
      tags: ['sports', 'free-event'],
      price: 0,
      sourceUrl: 'https://zeyzeymiami.com/tickets/',
    },
    {
      title: 'The Unofficial E.N.D Cruise Pre-Party',
      date: '2026-01-21',
      time: '19:00',
      venue: 'Zey Zey',
      address: '233 NE 2nd St, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7751,
      lng: -80.1897,
      city: 'Miami',
      category: 'Music',
      description: 'Pre-party for the E.N.D cruise. Get the party started before setting sail.',
      tags: ['dj', 'dancing', 'local-favorite'],
      price: 20,
      sourceUrl: 'https://zeyzeymiami.com/tickets/',
    },
    {
      title: 'Salsa Z ft. Elisa Baena + Cortadito (LIVE) + Safe Stadick',
      date: '2026-01-22',
      time: '19:00',
      venue: 'Zey Zey',
      address: '233 NE 2nd St, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7751,
      lng: -80.1897,
      city: 'Miami',
      category: 'Music',
      description: 'Live salsa night featuring Elisa Baena and Cortadito with DJ Safe Stadick. Dancing, cocktails, rooftop vibes.',
      tags: ['live-music', 'latin', 'dancing', 'local-favorite'],
      price: 20,
      sourceUrl: 'https://zeyzeymiami.com/tickets/',
    },
    {
      title: 'Anemoia + Afrobeta',
      date: '2026-01-23',
      time: '20:00',
      venue: 'Zey Zey',
      address: '233 NE 2nd St, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7751,
      lng: -80.1897,
      city: 'Miami',
      category: 'Music',
      description: 'Free show featuring Anemoia and Miami favorites Afrobeta. Electronic, synth-pop, and good vibes.',
      tags: ['live-music', 'electronic', 'free-event', 'local-favorite'],
      price: 0,
      sourceUrl: 'https://zeyzeymiami.com/tickets/',
    },
    {
      title: 'Booka Shade (Live)',
      date: '2026-01-24',
      time: '20:00',
      venue: 'Zey Zey',
      address: '233 NE 2nd St, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7751,
      lng: -80.1897,
      city: 'Miami',
      category: 'Music',
      description: 'German electronic duo Booka Shade performing live. Known for "Body Language" and their Get Physical releases.',
      tags: ['live-music', 'electronic', 'dj'],
      price: 35,
      sourceUrl: 'https://zeyzeymiami.com/tickets/',
    },
    {
      title: '3D Disco Presents: The Botanist',
      date: '2026-01-24',
      time: '22:00',
      venue: 'Zey Zey',
      address: '233 NE 2nd St, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7751,
      lng: -80.1897,
      city: 'Miami',
      category: 'Nightlife',
      description: '3D Disco party series featuring The Botanist. Expect disco, house, and funky grooves.',
      tags: ['dj', 'dancing', 'electronic'],
      price: 20,
      sourceUrl: 'https://zeyzeymiami.com/tickets/',
    },
    {
      title: 'Miami Is An Island Record Fair ft. Tony And The Kings',
      date: '2026-01-25',
      time: '16:00',
      venue: 'Zey Zey',
      address: '233 NE 2nd St, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7751,
      lng: -80.1897,
      city: 'Miami',
      category: 'Music',
      description: 'Vinyl record fair with live performance by Tony And The Kings. Dig through crates and discover new music.',
      tags: ['live-music', 'vinyl', 'local-favorite', 'pop-up'],
      price: 0,
      sourceUrl: 'https://zeyzeymiami.com/tickets/',
    },
    {
      title: 'Riff Raff - Houses Way In Tour',
      date: '2026-01-29',
      time: '19:00',
      venue: 'Zey Zey',
      address: '233 NE 2nd St, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7751,
      lng: -80.1897,
      city: 'Miami',
      category: 'Music',
      description: 'Riff Raff brings the Houses Way In Tour to Miami. The Houston rapper known for his eccentric style.',
      tags: ['live-music', 'hip-hop'],
      price: 30,
      sourceUrl: 'https://zeyzeymiami.com/tickets/',
    },
    {
      title: 'SUNNY RAVE w/ DJ Pressed',
      date: '2026-01-30',
      time: '22:00',
      venue: 'Zey Zey',
      address: '233 NE 2nd St, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7751,
      lng: -80.1897,
      city: 'Miami',
      category: 'Nightlife',
      description: 'Late night rave vibes with DJ Pressed. House, techno, and high energy on the rooftop.',
      tags: ['dj', 'electronic', 'dancing'],
      price: 15,
      sourceUrl: 'https://zeyzeymiami.com/tickets/',
    },
    {
      title: 'GoldFord - Space of the Heart Tour',
      date: '2026-01-31',
      time: '20:00',
      venue: 'Zey Zey',
      address: '233 NE 2nd St, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7751,
      lng: -80.1897,
      city: 'Miami',
      category: 'Music',
      description: 'GoldFord brings the Space of the Heart Tour to Miami. Soulful R&B and indie vibes.',
      tags: ['live-music', 'indie'],
      price: 25,
      sourceUrl: 'https://zeyzeymiami.com/tickets/',
    },
    {
      title: 'Modest Mouse (Second Show)',
      date: '2026-02-03',
      time: '19:00',
      venue: 'Zey Zey',
      address: '233 NE 2nd St, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7751,
      lng: -80.1897,
      city: 'Miami',
      category: 'Music',
      description: 'Indie rock legends Modest Mouse at Zey Zey. Known for "Float On" and "Dashboard".',
      tags: ['live-music', 'indie', 'local-favorite'],
      price: 45,
      sourceUrl: 'https://zeyzeymiami.com/tickets/',
    },
    {
      title: 'Modest Mouse',
      date: '2026-02-04',
      time: '19:00',
      venue: 'Zey Zey',
      address: '233 NE 2nd St, Miami, FL 33132',
      neighborhood: 'Downtown Miami',
      lat: 25.7751,
      lng: -80.1897,
      city: 'Miami',
      category: 'Music',
      description: 'Indie rock legends Modest Mouse at Zey Zey. Known for "Float On" and "Dashboard". SOLD OUT.',
      tags: ['live-music', 'indie', 'local-favorite'],
      price: 45,
      sourceUrl: 'https://zeyzeymiami.com/tickets/',
    },
  ];

  // Real events from Miami Beach Bandshell - https://miamibeachbandshell.com/events/
  private bandshellEvents: RealEvent[] = [
    {
      title: 'ScreenDance Miami Festival 2026',
      date: '2026-01-21',
      time: '19:30',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Culture',
      description: 'Dance films from around the world at the oceanfront Bandshell. A unique fusion of cinema and movement.',
      tags: ['theater', 'beach', 'local-favorite'],
      price: 20,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'South Beach Chamber Ensemble',
      date: '2026-01-25',
      time: '19:00',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'Classical music under the stars at the historic beachfront Bandshell. Bring a blanket.',
      tags: ['live-music', 'beach', 'local-favorite'],
      price: 25,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: "Miami Jewish Film Festival's Closing Night",
      date: '2026-01-29',
      time: '19:00',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Culture',
      description: 'Closing night celebration of the Miami Jewish Film Festival at the oceanfront Bandshell.',
      tags: ['theater', 'beach', 'cultural'],
      price: 30,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'Little Sing',
      date: '2026-02-01',
      time: '16:00',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Family',
      description: 'Interactive music experience for families with young children. Singing, dancing, and fun at the beach.',
      tags: ['family-friendly', 'beach', 'live-music'],
      price: 15,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'The Disco Biscuits',
      date: '2026-02-06',
      time: '19:30',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'Legendary jam band The Disco Biscuits at the Bandshell. Trance-fusion, improv, and beach vibes.',
      tags: ['live-music', 'beach', 'dancing'],
      price: 45,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'Locos Por Marley',
      date: '2026-02-07',
      time: '20:00',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'Bob Marley tribute concert in Spanish. Reggae classics reimagined with Latin flair.',
      tags: ['live-music', 'beach', 'latin'],
      price: 35,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'Portugal. The Man',
      date: '2026-02-11',
      time: '19:30',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'Grammy-winning rock band Portugal. The Man at the Bandshell. Known for "Feel It Still".',
      tags: ['live-music', 'beach', 'indie', 'local-favorite'],
      price: 55,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'Digable Planets',
      date: '2026-02-13',
      time: '20:00',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'Hip-hop legends Digable Planets. Jazz-infused rap classics like "Rebirth of Slick (Cool Like Dat)".',
      tags: ['live-music', 'hip-hop', 'jazz', 'beach'],
      price: 45,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'Molotov',
      date: '2026-02-15',
      time: '19:00',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'Mexican rock band Molotov brings their politically charged rap-rock to the beach.',
      tags: ['live-music', 'beach', 'latin'],
      price: 50,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'Krishna Das',
      date: '2026-02-20',
      time: '20:00',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Wellness',
      description: 'Grammy-nominated kirtan artist Krishna Das. Devotional chanting and meditation at the beach.',
      tags: ['live-music', 'beach', 'wellness', 'meditation'],
      price: 45,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'Celebrating the Miles Davis Centennial',
      date: '2026-02-25',
      time: '19:00',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'Special tribute concert celebrating 100 years of Miles Davis. Jazz legends perform his iconic works.',
      tags: ['live-music', 'jazz', 'beach', 'local-favorite'],
      price: 40,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'Makaya McCraven',
      date: '2026-02-26',
      time: '20:00',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'Genre-defying drummer and producer Makaya McCraven. Modern jazz meets hip-hop beats.',
      tags: ['live-music', 'jazz', 'beach', 'local-favorite'],
      price: 40,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'GroundUP Music Festival 2026 - Day 1',
      date: '2026-03-14',
      time: '12:30',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'Day 1 of GroundUP Music Festival. Snarky Puppy and friends bring world-class musicianship to the beach.',
      tags: ['live-music', 'jazz', 'beach', 'festival', 'local-favorite'],
      price: 125,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'GroundUP Music Festival 2026 - Day 2',
      date: '2026-03-15',
      time: '12:30',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'Day 2 of GroundUP Music Festival. More incredible performances from Snarky Puppy and collaborators.',
      tags: ['live-music', 'jazz', 'beach', 'festival', 'local-favorite'],
      price: 125,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'Global Cuba Fest 2026: Yusa and Friends',
      date: '2026-03-21',
      time: '20:00',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'Cuban singer Yusa headlines Global Cuba Fest. Afro-Cuban rhythms meet contemporary sounds.',
      tags: ['live-music', 'latin', 'beach', 'cultural', 'local-favorite'],
      price: 40,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'Cymande',
      date: '2026-03-25',
      time: '20:00',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'British funk legends Cymande return. Known for "Bra" and their influence on hip-hop.',
      tags: ['live-music', 'beach', 'local-favorite'],
      price: 45,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
    {
      title: 'moe.',
      date: '2026-03-28',
      time: '19:00',
      venue: 'Miami Beach Bandshell',
      address: '7275 Collins Ave, Miami Beach, FL 33141',
      neighborhood: 'North Beach',
      lat: 25.8648,
      lng: -80.1216,
      city: 'Miami',
      category: 'Music',
      description: 'Jam band legends moe. bring their improvisational rock to the beach. Extended jams guaranteed.',
      tags: ['live-music', 'beach'],
      price: 50,
      sourceUrl: 'https://miamibeachbandshell.com/events/',
    },
  ];

  constructor() {
    super('Real Venue Events', { weight: 1.5, rateLimit: 0 });
  }

  async scrape(): Promise<RawEvent[]> {
    const events: RawEvent[] = [];

    this.log('Processing real venue events...');

    // Add Zey Zey events
    for (const event of this.zeyZeyEvents) {
      events.push(this.convertToRawEvent(event));
    }

    // Add Bandshell events
    for (const event of this.bandshellEvents) {
      events.push(this.convertToRawEvent(event));
    }

    this.log(`Generated ${events.length} real venue events`);
    return events;
  }

  private convertToRawEvent(event: RealEvent): RawEvent {
    return {
      title: event.title,
      startAt: `${event.date}T${event.time}:00`,
      venueName: event.venue,
      address: event.address,
      neighborhood: event.neighborhood,
      lat: event.lat,
      lng: event.lng,
      city: event.city,
      tags: event.tags,
      category: event.category,
      priceLabel: event.price === 0 ? 'Free' : event.price > 75 ? '$$$' : event.price > 30 ? '$$' : '$',
      priceAmount: event.price,
      isOutdoor: event.tags.includes('beach') || event.tags.includes('rooftop'),
      description: event.description,
      sourceUrl: event.sourceUrl,
      sourceName: this.name,
      ticketUrl: event.ticketUrl || event.sourceUrl,
      recurring: false,
    };
  }
}
